baseURL = 'https://bbpeaches.com/'
locale = 'zh-cn'
defaultContentLanguage = 'zh'
title = 'Kaelen 的个人主页'
theme = 'PaperMod'

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  ShowReadingTime = true       # 显示预计阅读时间
  ShowWordCount = true         # 显示文章字数
  ShowToc = true               # 自动在长文章开头生成悬浮目录
  ShowCodeCopyButtons = true   # 代码块右上角开启“一键复制”按钮
  ShowBreadCrumbs = true       # 开启面包屑导航 (主页 > 专栏 > 文章)
  ShowPostNavLinks = true      # 文章底部显示“上一篇/下一篇”
  
  # 全局开启数学公式渲染支持
  math = true 

[params.homeInfoParams]
  Title = "欢迎来到我的数字花园 👋"
  Content = "你好！我是 Kaelen。"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/bbpeaches"
  [[params.socialIcons]]
    name = "email"
    url = "mailto:kaelenchow@gmail.com"

[menu]
  [[menu.main]]
    identifier = "search"
    name = "搜索🔍"
    url = "/search/"
    weight = 5
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 30