baseURL = 'https://bbpeaches.com/'
locale = 'zh-cn'
title = 'Kaelen 的个人主页'
theme = 'PaperMod'

[params.homeInfoParams]
  Title = "欢迎来到我的博客 \U0001F44B"
  Content = "这是我用来记录技术笔记和生活日常的地方。"

[menu]
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 30